# Generated by Django 2.2.16 on 2022-12-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20221203_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', max_length=16, verbose_name='Роль'),
        ),
    ]
