# Generated by Django 2.2.16 on 2022-12-06 10:37

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20221203_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(validators=[reviews.validators.validate_for_year], verbose_name='Дата выхода'),
        ),
    ]
