# Generated by Django 2.2.16 on 2022-12-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_auto_20221206_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Рейтинг'),
        ),
    ]
